Proper modularization of bash scripts for [CB-3627], but not solved yet. wait_for_emulator does not work atm

diff --git a/bin/templates/cordova/build b/bin/templates/cordova/build
--- a/bin/templates/cordova/build
+++ b/bin/templates/cordova/build
@@ -16,8 +16,24 @@
 # specific language governing permissions and limitations
 # under the License.
 
-set -e
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PROJECT_PATH=$( cd "$DIR/.." && pwd )
 
-CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd )
-
-bash "$CORDOVA_PATH"/lib/cordova build "$@"
+if [[ "$#" -eq 1 ]] ; then
+    if [[ $1 == "--debug" ]] ; then
+        $DIR/clean
+        ant debug -f "$PROJECT_PATH"/build.xml
+    elif [[ $1 == "--release" ]] ; then
+        $DIR/clean
+        ant release -f "$PROJECT_PATH"/build.xml
+    elif [[ $1 == "--nobuild" ]] ; then
+        echo "Skipping build..."
+    else
+        echo "Error : Build command '$1' not recognized."
+        exit 2
+    fi
+else
+    echo "Warning : [ --debug | --release | --nobuild ] not specified, defaulting to --debug"
+    $DIR/clean
+    ant debug -f "$PROJECT_PATH"/build.xml
+fi
diff --git a/bin/templates/cordova/lib/install-emulator b/bin/templates/cordova/lib/install-emulator
--- a/bin/templates/cordova/lib/install-emulator
+++ b/bin/templates/cordova/lib/install-emulator
@@ -16,8 +16,35 @@
 # specific language governing permissions and limitations
 # under the License.
 
-set -e
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PROJECT_PATH=$( cd "$DIR/../.." && pwd )
+emulator_list=$("$DIR/list-started-emulators")
+if [ $? != 0 ]; then
+    echo "No emulators found to deploy to. Please make sure your emulator is started"
+    echo " You can view it using the 'cordova/lib/list-started-emulators' command."
+    echo " You can view created emulator images using the 'cordova/lib/list-emulator-images' command."
+    echo " You can start an emulator image using the 'cordova/lib/start-emulator' command."
+    exit 2
+fi
 
-CORDOVA_LIB_PATH=$( cd "$( dirname "$0" )" && pwd )
-
-bash "$CORDOVA_LIB_PATH"/cordova install-emulator "$@"
+apks=`find $PROJECT_PATH/bin -type f -maxdepth 1 | egrep '\.apk$'`
+apk_list=($apks)
+if [[ ${#apk_list[@]} > 0 ]] ; then
+    # handle target emulator
+    if [[ "$#" -eq 1 ]] ; then
+        # deploy to given target
+        target=${1/--target=/}
+    else
+        # delete trailing space and 'device' after emulator ID
+        target=${emulator_list[0]}
+    fi
+    echo "Installing ${apk_list[0]} onto emulator $target..."
+    adb -s $target install -r ${apk_list[0]};
+    echo "Launching application..."
+    launch_str=$(java -jar "$PROJECT_PATH"/cordova/appinfo.jar "$PROJECT_PATH"/AndroidManifest.xml)
+    adb -s $target shell am start -W -a android.intent.action.MAIN -n $launch_str
+else
+    echo "Application package not found, could not install to device"
+    echo " make sure your application is built before deploying."
+    exit 2
+fi
diff --git a/bin/templates/cordova/lib/start-emulator b/bin/templates/cordova/lib/start-emulator
--- a/bin/templates/cordova/lib/start-emulator
+++ b/bin/templates/cordova/lib/start-emulator
@@ -16,8 +16,30 @@
 # specific language governing permissions and limitations
 # under the License.
 
-set -e
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PROJECT_PATH=$( cd "$( dirname "$0" )/../.." && pwd )
+emulator_images=$("$DIR/list-emulator-images")
+if [ $? != 0 ]; then
+    echo "No emulators found, if you would like to create an emulator follow the instructions"
+    echo " provided here : http://developer.android.com/tools/devices/index.html"
+    echo " Or run 'android create avd --name <name> --target <targetID>' in on the command line."
+    exit 2
+fi
 
-CORDOVA_LIB_PATH=$( cd "$( dirname "$0" )" && pwd )
-
-bash "$CORDOVA_LIB_PATH"/cordova start-emulator "$@"
+# if target emulator is provided
+if [[ "$#" -eq 1 ]] ; then
+    # check that it exists
+    if [[ $emulator_images =~ $1 ]] ; then
+        #xterm -e emulator -avd $1 &
+        emulator -avd $1 1> /dev/null 2>&1 &
+    else
+        echo "Could not find the provided emulator '$1', make sure the emulator exists"
+        echo " by checking 'cordova/lib/list-emulator-images'"
+        exit 2
+    fi
+else
+    # start first emulator
+    read -ra emulator_list <<< "$emulator_images"
+    #xterm -e emulator -avd ${emulator_list[0]} &
+    emulator -avd ${emulator_list[0]} 1> /dev/null 2>&1 &
+fi
diff --git a/bin/templates/cordova/run b/bin/templates/cordova/run
--- a/bin/templates/cordova/run
+++ b/bin/templates/cordova/run
@@ -16,8 +16,109 @@
 # specific language governing permissions and limitations
 # under the License.
 
-set -e
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PROJECT_PATH=$( cd "$DIR/.." && pwd )
 
-CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd )
+function wait_for_emulator {
+# TODO: this doesnt seem to work
+    emulator_string=$("$DIR/lib/list-started-emulators")
+    old_started=($emulator_string)
+    local new_started
+    local new_emulator_name
+    local i="0"
+    echo -n "Waiting for emulator..."
+    while [ $i -lt 300 ]
+    do
+        emulator_string=$("$DIR/lib/list-started-emulators")
+        new_started=($emulator_string)
+        if [[ ${#new_started[@]} > ${#old_started[@]} && -z "$new_emulator_name" ]] ; then
+            # get the name of the started emulator
+            local count="0"
+            if [[ ${#old_started[@]} == 0 ]] ; then
+                new_emulator_name=${new_started[$count]}
+            else
+                for count in {0...${#old_started[@]}}
+                do
+                    if [[ ! ${new_started[$count]} == ${old_started[$count]} ]] ; then
+                        new_emulator_name=${new_started[$count]}
+                    fi
+                done
+                if [[ -z "$new_emulator_name" ]] ; then
+                    count=$[count+1]
+                    new_emulator_name=${new_started[$count]}
+                fi
+            fi
+        elif [[ "$new_emulator_name" ]] ; then
+            boot_anim=`adb -s $new_emulator_name shell getprop init.svc.bootanim`
+            if [[ $boot_anim =~ "stopped" ]] ; then
+                break
+            else
+                sleep 1
+                i=$[i+1]
+                echo -n "."
+            fi
+        else
+            sleep 1
+            i=$[i+1]
+            echo -n "."
+        fi
+    done
+    # Device timeout: emulator has not started in time
+    if [ $i -eq 300 ]
+    then
+        echo "emulator timeout!"
+        exit 69
+    else
+        echo "connected!"
+    fi
+}
 
-bash "$CORDOVA_PATH"/lib/cordova run "$@"
+if [[ "$#" -eq 2 ]] ; then
+    $DIR/build $2
+    if [[ $1 == "--device" ]] ; then
+        $DIR/lib/install_device
+    elif [[ $1 == "--emulator" ]] ; then
+        $DIR/lib/install_emulator
+    elif [[ $1 =~ "--target=" ]]; then
+        $DIR/lib/install_device $1
+    else
+        echo "Error : '$1' is not recognized as an install option"
+    fi
+elif [[ "$#" -eq 1 ]] ; then
+    if [[ $1 == "--debug" || $1 == "--release" || $1 == "--nobuild" ]] ; then
+        $DIR/build $1
+    elif [[ $1 == "--device" ]] ; then
+        $DIR/build
+        $DIR/lib/install_device
+    elif [[ $1 == "--emulator" ]] ; then
+        $DIR/build
+        $DIR/lib/install_emulator
+    elif [[ $1 =~ "--target=" ]]; then
+        $DIR/build
+        $DIR/lib/install_device $1
+    else
+        echo "Error : '$1' is not recognized as an install option"
+    fi
+else
+    echo "Warning : [ --device | --emulate | --target=<targetID> ] not specified, using defaults."
+    #$DIR/build
+    devices=$("$DIR/lib/list-devices")
+    if [ $? = 0 ]; then
+        $DIR/lib/install_device
+    else
+        emulators=$("$DIR/lib/list-started-emulators")
+        if [ $? = 0 ] ; then
+            $DIR/lib/install_emulator
+        else
+            images=$("$DIR/lib/list-emulator-images")
+            if [ $? = 0 ] ; then
+                $DIR/lib/start-emulator
+                wait_for_emulator
+                $DIR/lib/install_emulator
+            else
+                echo "No Android devices attached, nor emulator images available to start. How are we supposed to do this, then?"
+                exit 2
+            fi
+        fi
+    fi
+fi
