[CB-3627] start-emulator now properly starts, waits for and unlocks an emulator, consumed by run as well.

diff --git a/bin/templates/cordova/lib/start-emulator b/bin/templates/cordova/lib/start-emulator
--- a/bin/templates/cordova/lib/start-emulator
+++ b/bin/templates/cordova/lib/start-emulator
@@ -18,6 +18,50 @@
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 PROJECT_PATH=$( cd "$( dirname "$0" )/../.." && pwd )
+
+function dot {
+    sleep 1
+    echo -n "."
+}
+
+function wait_for_emulator {
+    local i="0"
+    echo -n "Waiting for emulator"
+    emulator_string=$($DIR/list-started-emulators)
+    while [ $? != 0 ]
+    do
+        dot
+        i=$[i+1]
+        emulator_string=$($DIR/list-started-emulators)
+    done
+    read -ra target <<< "$emulator_string"
+    echo ""
+    echo -n "Waiting for it to boot up (this can take a while)"
+    while [ $i -lt 300 ]
+    do
+        boot_anim=$(adb -s $target shell getprop init.svc.bootanim 2>&1)
+        if [[ "$boot_anim" =~ "stopped" ]] ; then
+            break
+        else
+            i=$[i+1]
+            dot
+        fi
+    done
+    # Device timeout: emulator has not started in time
+    if [ $i -eq 300 ]
+    then
+        echo ""
+        echo "Emulator timeout!"
+        exit 69
+    else
+        echo ""
+        echo "Connected!"
+    fi
+    # Unlock the device
+    adb -s $target shell input keyevent 82
+    exit 0
+}
+
 emulator_images=$("$DIR/list-emulator-images")
 if [ $? != 0 ]; then
     echo "No emulators found, if you would like to create an emulator follow the instructions"
@@ -43,3 +87,5 @@ else
     #xterm -e emulator -avd ${emulator_list[0]} &
     emulator -avd ${emulator_list[0]} 1> /dev/null 2>&1 &
 fi
+
+wait_for_emulator
